spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: update
  mvc:
    static-path-pattern: /static/**

jwt:
  token:
    secret: "fff"